=== HmingWang/Center-Java/schema/szfs.301.002.01.xsd
<?xml version="1.0" encoding="GBK"?>
<xs:schema xmlns="urn:szfs:std:szfs:2010:tech:xsd:szfs.301.002.01" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="urn:szfs:std:szfs:2010:tech:xsd:szfs.301.002.01" elementFormDefault="qualified">
	<xs:element name="Document" type="Document"/>
	<xs:complexType name="Document">
		<xs:sequence>
			<xs:element name="PmtByAgcy" type="PaymentByAgency"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PaymentByAgency">
		<xs:sequence>
			<xs:element name="GrpHdr" type="GroupHeader1"/>
			<xs:element name="PmtByAgcyInf" type="PaymentByAgencyInformation"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="GroupHeader1">
		<xs:sequence>
			<xs:element name="TxTpCd" type="Exact3NumericText"/>
			<xs:element name="CnsDt" type="Exact8NumericText"/>
			<xs:element name="TxId" type="Max8NumericText"/>
			<xs:element name="InstgPty" type="Max14Text"/>
			<xs:element name="Ccy" type="Currencycode1"/>
			<xs:element name="Amt" type="Max15NumericText"/>
			<xs:element name="TxCd" type="Exact5NumericText"/>
			<xs:element name="Areacd" type="AreaCode1"/>
			<xs:element name="AcctChckFlg" type="AcctChckFlgCode1" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PaymentByAgencyInformation">
		<xs:sequence>
			<xs:element name="CorprtnId" type="Max14Text"/>
			<xs:element name="DbtrId" type="Max14Text"/>
			<xs:element name="CdtrId" type="Max14Text"/>
			<xs:element name="Dbtr" type="Debtor1"/>
			<xs:element name="Cdtr" type="Creditor1"/>
			<xs:element name="PmtItmCd" type="Max5Text"/>
			<xs:element name="ChanlId" type="Exact4Text" minOccurs="0"/>
			<xs:element name="Rmk" type="Max127Text" minOccurs="0"/>
			<xs:element name="AltDbtrFlg" type="AltDbtrFlgCode1" minOccurs="0"/>
			<xs:element name="AltDbtrNm" type="Max60Text" minOccurs="0"/>	
			<xs:element name="ProCd" type="Exact5Text" minOccurs="0"/>
			<xs:element name="TxFlg" type="Exact2Text" minOccurs="0"/>		
			<xs:element name="AddtlLen" type="Max8NumericText"/>
			<xs:element name="AddtlInf" type="AdditionalInformation1" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AdditionalInformation1">
		<xs:sequence>
			<xs:element name="Cntt" type="Max4000Text"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Debtor1">
		<xs:sequence>
			<xs:element name="Issr" type="Max14Text"/>
			<xs:element name="Id" type="Max32Text" minOccurs="0"/>
			<xs:element name="Nm" type="Max60Text" minOccurs="0"/>
			<xs:element name="Adr" type="Max60Text" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Creditor1">
		<xs:sequence>
			<xs:element name="Issr" type="Max14Text"/>
			<xs:element name="Id" type="Max32Text"/>
			<xs:element name="Nm" type="Max60Text" minOccurs="0"/>
			<xs:element name="Adr" type="Max60Text" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="Exact3NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="3"/>
			<xs:maxLength value="3"/>
			<xs:pattern value="[0-9]{1,3}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Exact8NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="8"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="[0-9]{1,8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max8NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="8"/>
			<xs:pattern value="[0-9]{1,8}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISODateTime">
		<xs:restriction base="xs:dateTime"/>
	</xs:simpleType>
	<xs:simpleType name="Max14Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="8"/>
			<xs:maxLength value="14"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Currencycode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="CNY"/>
			<xs:enumeration value="USD"/>
			<xs:enumeration value="HKD"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DecimalNumber">
		<xs:restriction base="xs:decimal">
			<xs:fractionDigits value="2"/>
			<xs:totalDigits value="15"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Exact5NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="5"/>
			<xs:maxLength value="5"/>
			<xs:pattern value="[0-9]{1,5}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AreaCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="005840"/>
			<xs:enumeration value="000000"/>
			<xs:enumeration value="999999"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AcctChckFlgCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="BillIndicatorCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max127Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="127"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max32Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="32"/>
			<xs:pattern value="[a-zA-Z0-9\-_]{1,32}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max60Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="60"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max15NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="15"/>
			<xs:pattern value="[0-9]{1,15}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max2NumericText">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="2"/>
			<xs:pattern value="[0-9]{1,2}"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="ISODate">
		<xs:restriction base="xs:date"/>
	</xs:simpleType>
	<xs:simpleType name="Max4000Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="4000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max5Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="5"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Exact2Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="2"/>
			<xs:maxLength value="2"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Exact4Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="4"/>
			<xs:maxLength value="4"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Exact5Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="5"/>
			<xs:maxLength value="5"/>
		</xs:restriction>
	</xs:simpleType>	
	<xs:simpleType name="DerivFlgcode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="1"/>
			<xs:enumeration value="2"/>
			<xs:enumeration value="3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AlltdFlgcode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AcctChckFlgcode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="Max12Text">
		<xs:restriction base="xs:string">
			<xs:minLength value="1"/>
			<xs:maxLength value="12"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AltDbtrFlgCode1">
		<xs:restriction base="xs:string">
			<xs:enumeration value="0"/>
			<xs:enumeration value="1"/>
		</xs:restriction>
	</xs:simpleType>		
</xs:schema>

=== HmingWang/Center-Java/xml/301.xml
{H:0110258409999F                SZFS0                            SZFS020140401094508XMLSZFS.301.002.01     00000000000000000000000000000000000000003U         }
{S:b264ec118771df7762df6e6be042e990a6c51acdc1ae41d48d16d4d52b3782f3c79a16b8b0c3fdb0711abc419e4ff2512e8fa917af77677a7255dd20df961e76b659f6e01d4dada1e986755bd448f40da80040ca9a34d92603b351a3329b9c8e3d114ce2f7bc0e81387cf26a14ae0a596b4e561312157f2de98c9c194eab0237dcd5c65da4e1c40f3a08aa5ec8a9d66a4ab05bf63076d172f17717097406cefce6dbbb350e09a6312dd22c0876f0d51596dbd3f6c08fdf47ee96bf384fe59934addc6d6f8931b0b4f2b1998f890f6dc624ae5d00cccf8bf98b2c26bc894f666edd424d81088ff1f0f9fc8e4d2cc4a7393c3edd51d87f4b032198b6f36beba225                                                                                                                                }
<?xml version="1.0" encoding="GBK"?>
<Document xmlns="urn:szfs:std:szfs:2010:tech:xsd:szfs.301.002.01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:szfs:std:szfs:2010:tech:xsd:szfs.301.002.01
/home/szfscp/test/schema/szfs.301.002.01.xsd">
	<PmtByAgcy>
		<GrpHdr>
			<TxTpCd>301</TxTpCd>
			<CnsDt>20160421</CnsDt>
			<TxId>4351041</TxId>
			<InstgPty>A00100000001  </InstgPty>
			<Ccy>CNY</Ccy>
			<Amt>1600</Amt>
			<TxCd>30102</TxCd>
			<Areacd>005840</Areacd>
			<AcctChckFlg>0</AcctChckFlg>
		</GrpHdr>
		<PmtByAgcyInf>
			<CorprtnId>A00100000001  </CorprtnId>
			<DbtrId>302584043105</DbtrId>
			<CdtrId>303584000004</CdtrId>
			<Dbtr>
				<Issr>302584043105</Issr>
				<Id>61000001</Id>
				<Nm>测试账号一</Nm>
				<Adr>替换户名付款人地址</Adr>
			</Dbtr>
			<Cdtr>
				<Issr>303584000004</Issr>
				<Id>61000005</Id>
				<Nm>测试账号5</Nm>
				<Adr>收款人地址在哪里</Adr>
			</Cdtr>
			<PmtItmCd>00800</PmtItmCd>
			<Rmk>合昏尚知时，鸳鸯不独宿。但见新人笑，那闻旧人哭。</Rmk>
			<AltDbtrFlg>0</AltDbtrFlg>
			<AltDbtrNm>---乌合之众-123-保险有限公司</AltDbtrNm>
			<ProCd>301A1</ProCd>
			<AddtlLen>361</AddtlLen>
			<AddtlInf>
				<Cntt>30101                                二期优化测试                                                                                                                                                                                                                                                                                                                        </Cntt>
			</AddtlInf>
		</PmtByAgcyInf>
	</PmtByAgcy>
</Document>

=== HmingWang/Center-Java/src/main/resources/xml/sample.xml
<?xml version="1.0" encoding="GBK"?>
<Document xmlns="urn:szfs:std:szfs:2010:tech:xsd:szfs.301.002.01" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="urn:szfs:std:szfs:2010:tech:xsd:szfs.301.002.01
/schema/szfs.301.002.01.xsd">
    <PmtByAgcy>
        <GrpHdr>
            <TxTpCd>301</TxTpCd>
            <CnsDt>20160421</CnsDt>
            <TxId>4351041</TxId>
            <InstgPty>A00100000001  </InstgPty>
            <Ccy>CNY</Ccy>
            <Amt>1600</Amt>
            <TxCd>30102</TxCd>
            <Areacd>005840</Areacd>
            <AcctChckFlg>0</AcctChckFlg>
        </GrpHdr>
        <PmtByAgcyInf>
            <CorprtnId>A00100000001  </CorprtnId>
            <DbtrId>302584043105</DbtrId>
            <CdtrId>303584000004</CdtrId>
            <Dbtr>
                <Issr>302584043105</Issr>
                <Id>61000001</Id>
                <Nm>????????</Nm>
                <Adr>?ùI????????????</Adr>
            </Dbtr>
            <Cdtr>
                <Issr>303584000004</Issr>
                <Id>61000005</Id>
                <Nm>???????5</Nm>
                <Adr>?????????????</Adr>
            </Cdtr>
            <PmtItmCd>00800</PmtItmCd>
            <Rmk>?????????????????????????ß∏???????????</Rmk>
            <AltDbtrFlg>0</AltDbtrFlg>
            <AltDbtrNm>---??????-123-??????????</AltDbtrNm>
            <ProCd>301A1</ProCd>
            <AddtlLen>361</AddtlLen>
            <AddtlInf>
                <Cntt>30101                                ???????????                                                                                                                                                                                                                                                                                                                        </Cntt>
            </AddtlInf>
        </PmtByAgcyInf>
    </PmtByAgcy>
</Document>
